-- SQL Schema for Marien's 40th Birthday Celebration Website
-- Standard Snake Case schema for maximum compatibility and reliability.
-- Run this in the Supabase Dashboard SQL Editor (https://app.supabase.com/project/_/sql)

-- 1. Drop existing tables for a clean slate
DROP TABLE IF EXISTS rsvps CASCADE;
DROP TABLE IF EXISTS itinerary CASCADE;

-- 2. Create Itinerary Table
CREATE TABLE IF NOT EXISTS itinerary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day TEXT NOT NULL,
  title TEXT NOT NULL,
  time TEXT NOT NULL,
  description TEXT,
  dress_code TEXT,
  location TEXT, event_date DATE, start_time TIME,
  is_highlight BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create RSVPs Table
CREATE TABLE IF NOT EXISTS rsvps (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  attending_gala BOOLEAN DEFAULT FALSE,
  attending_brunch BOOLEAN DEFAULT FALSE,
  dietary_notes TEXT,
  adult_count INTEGER DEFAULT 1,
  child_count INTEGER DEFAULT 0,
  adult_names TEXT, -- Comma separated or JSON string
  child_names TEXT, -- Comma separated or JSON string
  message TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enabling Row Level Security (RLS)
ALTER TABLE itinerary ENABLE ROW LEVEL SECURITY;
ALTER TABLE rsvps ENABLE ROW LEVEL SECURITY;

-- Policies for Itinerary
DROP POLICY IF EXISTS "Allow public read-only access to itinerary" ON itinerary;
CREATE POLICY "Allow public read-only access to itinerary" 
ON itinerary FOR SELECT USING (true);

-- Policies for RSVPs
DROP POLICY IF EXISTS "Allow public submissions for RSVPs" ON rsvps;
CREATE POLICY "Allow public submissions for RSVPs" 
ON rsvps FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to view RSVPs" ON rsvps;
CREATE POLICY "Allow authenticated users to view RSVPs" 
ON rsvps FOR SELECT USING (true); -- This should be restricted later with Auth

-- 5. Enable Realtime for live updates
-- Run this to allow the Admin Dashboard to sync instantly when a guest submits
ALTER PUBLICATION supabase_realtime ADD TABLE rsvps;
ALTER PUBLICATION supabase_realtime ADD TABLE itinerary;
